{
 "title": "Beacon",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prysm Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prysm_version{buildDate=\"1671146586\", commit=\"3d6d0a12dd189abcd2cfbba1c3d56505a1dd595c\", instance=\"localhost:8080\", job=\"beacon node\", version=\"v3.2.0\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Beacon Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Beacon Head Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_head_slot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slots behind",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "Beacondb Pending Deposits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacondb_pending_deposits{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node process started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600"
    }
   ]
  },
  {
   "title": "Powchain Block Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powchain_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "P2P Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1.5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"beacon node\"}",
     "legendFormat": "beacon node"
    }
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1.5, "w": 12, "x": 12, "y": 13.5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Hardware usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"beacon node\"}[1m:5s])",
     "legendFormat": "memory {{job}}"
    },
    {
     "expr": "((process_cpu_seconds_total{job=\"beacon node\"} - process_cpu_seconds_total{job=\"beacon node\"} offset 2m) > 0)*100/120/go_maxprocs{job=\"beacon node\"}",
     "legendFormat": "CPU {{job}}"
    }
   ]
  }
 ]
}